# Copyright (c) 2008-2023 the Urho3D project
# Copyright (c) 2022-2023 the Dviglo project
# License: MIT

name: CI/CD
on:
  push:
  pull_request:
  repository_dispatch: { types: [ 'Warm DBE build cache' ] }
jobs:
  init:
    name: Init
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.whatchanged.outputs.skip }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: What changed
        id: whatchanged
        run: |
          git fetch --deepen=1
          git log --raw --no-merges -1 |grep '^:' >/tmp/whatchanged
          echo "name=skip::$(grep -cqv 'website/' /tmp/whatchanged; echo $?)" >> $GITHUB_OUTPUT

  Windows:
    # Job будет запущен на виртуальной машине с новейшей версией Windows
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on
    # https://github.com/actions/runner-images
    runs-on: windows-latest

    # Используем матрицу для параллельной сборки разных билдов
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategy
    strategy:
      fail-fast: false
      matrix:
        COMPILER: [vs, mingw]
        DV_SHARED:
        - {
            ID: static,
            VALUE: 0,
          }
        - {
            ID: shared,
            VALUE: 1,
          }
        BUILD_TYPE: [debug, release]

    # Отображаемое имя job
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idname
    name: 🔲-${{ matrix.COMPILER }}-${{ matrix.DV_SHARED.ID }}-${{ matrix.BUILD_TYPE }}

    steps:
      # Используем MSYS2 вместо устаревшего MinGW
      # https://github.com/urho3d/urho3D/issues/2887
    - name: Устанавливаем MinGW
      if: matrix.COMPILER == 'mingw'
      # https://www.msys2.org/docs/ci/
      # https://github.com/msys2/setup-msys2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: mingw-w64-x86_64-toolchain

    - name: Добавляем в PATH путь к MinGW
      if: matrix.COMPILER == 'mingw'
      shell: bash
      # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-system-path
      run: echo "${RUNNER_TEMP}/msys64/mingw64/bin" >> $GITHUB_PATH

    - name: Устанавливаем остальной софт
      shell: bash
      run: |
        choco install --no-progress graphviz.portable

        # choco качает Doxygen через раз. Качаем собственную сборку
        mkdir $GITHUB_WORKSPACE/programs
        cd $GITHUB_WORKSPACE/programs
        curl -Lso tmp.zip https://github.com/dviglo-tools/doxygen-builder/raw/main/doxygen_win64.zip && unzip tmp.zip && rm tmp.zip
        echo "$GITHUB_WORKSPACE/programs" >> $GITHUB_PATH
        echo "Собственная сборка Doxygen скачана в $GITHUB_WORKSPACE/programs"

    - name: Скачиваем репозиторий
      # https://github.com/actions/checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        path: repo # Папка, в которую будет скачан репозиторий

    - name: Скачиваем кэш
      uses: actions/cache@v3
      with:
        path: build
        key: windows-${{ matrix.COMPILER }}-${{ matrix.DV_SHARED.ID }}-${{ matrix.BUILD_TYPE }}-${{ github.sha }}
        restore-keys: windows-${{ matrix.COMPILER }}-${{ matrix.DV_SHARED.ID }}-${{ matrix.BUILD_TYPE }}

      # https://docs.github.com/en/actions/learn-github-actions/expressions
      # https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
      # https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#push
      # https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request
    - name: Удаляем кэш по запросу пользователя
      if: |
        (github.event_name == 'pull_request' && contains(github.event.pull_request.title, '[clear cache]')) ||
        (github.event_name == 'push' && contains(join(github.event.commits.*.message, ' '), '[clear cache]'))
      shell: bash
      run: |
        rm -rf build

    - name: Генерируем проекты
      shell: bash
      run: |
        ARGS=(repo -B build) # Массив аргументов

        if [ "${{ matrix.COMPILER }}" == "vs" ]
        then
          ARGS+=(-G "Visual Studio 17 2022")
        else
          ARGS+=(-G "MinGW Makefiles")
          # Для MinGW тип сбоки задаётся при генерации проектов
          ARGS+=(-D CMAKE_BUILD_TYPE=${{ matrix.BUILD_TYPE }})
        fi

        ARGS+=(-D DV_SHARED=${{ matrix.DV_SHARED.VALUE }})
        ARGS+=(-D DV_TESTING=1)

        cmake "${ARGS[@]}"

    - name: Компилируем
      shell: bash
      run: |
        ARGS=(--build build) # Массив аргументов

        if [ "${{ matrix.COMPILER }}" == "vs" ]
        then
          # Для Visual Studio тип сбоки задаётся при компиляции проектов
          ARGS+=(--config ${{ matrix.BUILD_TYPE }})
        fi

        cmake "${ARGS[@]}"

      # Виртуальная машина ГитХаба может запускать Direct3D-приложения,
      # но не может запускать OpenGL-приложения. Поэтому используем
      # предкомпилированный Mesa 3D for Windows
    - name: Качаем Mesa 3D
      shell: bash
      run: |
        # Качаем и распаковываем Mesa 3D
        # https://curl.se/docs/manpage.html
        curl.exe --location --output mesa.7z --url https://github.com/pal1000/mesa-dist-win/releases/download/22.2.3/mesa3d-22.2.3-release-msvc.7z
        7z x mesa.7z -omesa
        rm mesa.7z

        # Перемещаем нужные dll в папку bin
        #mv mesa/x64/dxil.dll build/bin # Используется при эмуляции через DirectX
        mv mesa/x64/libgallium_wgl.dll build/bin
        mv mesa/x64/libglapi.dll build/bin
        mv mesa/x64/opengl32.dll build/bin

    - name: CTest
      shell: bash {0} # Разрешаем перехват ошибок
      run: |
        ARGS=(--test-dir build --timeout 60) # Массив аргументов

        if [ "${{ matrix.COMPILER }}" == "vs" ]
        then
          # Для Visual Studio нужно указывать тип сборки (конфигурацию)
          ARGS+=(-C ${{ matrix.BUILD_TYPE }})
        fi

        # Настройка для Mesa (не используем DirectX для эмуляции).
        # Без этого не проходит тест примера pbr_materials.
        # https://docs.mesa3d.org/envvars.html
        export LIBGL_ALWAYS_SOFTWARE=true

        ctest "${ARGS[@]}"
        EXIT_CODE=$? # Код возврата предыдущей команды

        if (( $EXIT_CODE != 0 )) 
        then
          echo "$(cat $APPDATA/dviglo/logs/CrowdNavigation.log)" # Показываем содержимое лога
          exit $EXIT_CODE
        fi

  Linux_Native:
    runs-on: ubuntu-latest
    needs: init
    if: needs.init.outputs.skip == '0'

    strategy:
      fail-fast: false
      matrix:
        COMPILER:
        - {
            ID: gcc,
            #C: gcc,
            #CXX: g++,
            C: gcc-12, # Используем GCC 12 вместо дефолтного 11, так как 11 не поддерживает shared_ptr<T[]>
            CXX: g++-12,
          }
        - {
            ID: clang,
            C: clang,
            CXX: clang++,
          }
        DV_SHARED:
        - {
            ID: static,
            VALUE: 0,
          }
        - {
            ID: shared,
            VALUE: 1,
          }
        BUILD_TYPE:
        - {
            ID: dbg,
            VALUE: Debug,
          }
        - {
            ID: rel,
            VALUE: Release,
          }

    name: 🐧-${{ matrix.COMPILER.ID }}-${{ matrix.DV_SHARED.ID }}-${{ matrix.BUILD_TYPE.ID }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with: { path: "engine_repo" }

    - name: Install dependencies
      run: |
        sudo apt update
        # Без libxrandr-dev не получится узнать список поддерживаемых разрешений
        sudo apt install libgl1-mesa-dev libxrandr-dev libxi-dev

        # Репозиторий Ubuntu содержит устаревшую версию Doxygen 1.9.1. Качаем собственную сборку
        mkdir $HOME/programs
        cd $HOME/programs
        wget -q -O tmp.zip https://github.com/dviglo-tools/doxygen-builder/raw/main/doxygen_linux64.zip && unzip tmp.zip && rm tmp.zip
        echo "$HOME/programs" >> $GITHUB_PATH

    - name: Скачиваем кэш
      uses: actions/cache@v3
      with:
        path: engine_build
        key: linux-${{ matrix.COMPILER.ID }}-${{ matrix.DV_SHARED.ID }}-${{ matrix.BUILD_TYPE.ID }}-${{ github.sha }}
        restore-keys: linux-${{ matrix.COMPILER.ID }}-${{ matrix.DV_SHARED.ID }}-${{ matrix.BUILD_TYPE.ID }}

      # https://docs.github.com/en/actions/learn-github-actions/expressions
      # https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
      # https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#push
      # https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request
    - name: Удаляем кэш по запросу пользователя
      if: |
        (github.event_name == 'pull_request' && contains(github.event.pull_request.title, '[clear cache]')) ||
        (github.event_name == 'push' && contains(join(github.event.commits.*.message, ' '), '[clear cache]'))
      run: |
        rm -rf engine_build

    - name: Build
      run: |
        #set -x # Echo commands
        echo "Current dir: $PWD"

        cmake engine_repo -B engine_build -G "Unix Makefiles" \
          -D CMAKE_C_COMPILER=${{ matrix.COMPILER.C }} -D CMAKE_CXX_COMPILER=${{ matrix.COMPILER.CXX }} \
          -D DV_TESTING=1 -D CMAKE_BUILD_TYPE=${{ matrix.BUILD_TYPE.VALUE }} \
          -D DV_SHARED=${{ matrix.DV_SHARED.VALUE }}

        cmake --build engine_build

    - name: CTest
      shell: bash {0} # Allow catching errors
      run: |
        xvfb-run ctest --test-dir engine_build
        EXIT_CODE=$? # Exit code of the previous command

        if (( $EXIT_CODE != 0 )) 
        then
          echo "$(cat ~/.local/share/dviglo/logs/CrowdNavigation.log)"
          exit $EXIT_CODE
        fi

    - name: Test tools
      run: $GITHUB_WORKSPACE/engine_repo/script/test_tools.sh $GITHUB_WORKSPACE/engine_repo $GITHUB_WORKSPACE/engine_build

    - name: Test app
      if: false
      run: |
        #cmake --install engine_build --prefix=$HOME/installed_engine # Not works
        #DV_HOME=$HOME/installed_engine # Not works (add export?)
        #DV_HOME=$GITHUB_WORKSPACE/engine_build # Not works
        sudo cmake --build engine_build --target install
        cd engine_repo
        rake new
        cd ..

        cmake $HOME/projects/UrhoApp -B $HOME/projects/UrhoApp_build -G "Unix Makefiles" \
          -D CMAKE_C_COMPILER=${{ matrix.COMPILER.C }} -D CMAKE_CXX_COMPILER=${{ matrix.COMPILER.CXX }} \
          -D DV_TESTING=1 -D CMAKE_BUILD_TYPE=${{ matrix.BUILD_TYPE.VALUE }} \
          -D DV_SHARED=${{ matrix.DV_SHARED.VALUE }}

        cmake --build $HOME/projects/UrhoApp_build
        xvfb-run ctest --test-dir $HOME/projects/UrhoApp_build

  Linux_MinGW:
    runs-on: ubuntu-22.04
    needs: init
    if: false # Не работает в Ubuntu 22.04

    strategy:
      fail-fast: false
      matrix:
        DV_SHARED:
        - {
            ID: static,
            VALUE: 0,
          }
        - {
            ID: shared,
            VALUE: 1,
          }
        BUILD_TYPE:
        - {
            ID: dbg,
            VALUE: Debug,
          }
        - {
            ID: rel,
            VALUE: Release,
          }

    name: 🐧-mingw-${{ matrix.DV_SHARED.ID }}-${{ matrix.BUILD_TYPE.ID }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with: { path: engine_repo }

    - name: Install dependencies
      run: sudo apt install mingw-w64

    - name: Скачиваем кэш
      uses: actions/cache@v3
      with:
        path: engine_build
        key: linux-mingw-${{ matrix.DV_SHARED.ID }}-${{ matrix.BUILD_TYPE.ID }}-${{ github.sha }}
        restore-keys: linux-mingw-${{ matrix.DV_SHARED.ID }}-${{ matrix.BUILD_TYPE.ID }}

    - name: Удаляем кэш по запросу пользователя
      if: |
        (github.event_name == 'pull_request' && contains(github.event.pull_request.title, '[clear cache]')) ||
        (github.event_name == 'push' && contains(join(github.event.commits.*.message, ' '), '[clear cache]'))
      run: |
        rm -rf engine_build

    - name: Build
      run: |
        #set -x # Echo commands
        echo "Current dir: $PWD" # $GITHUB_WORKSPACE

        export MINGW_PREFIX=/usr/bin/x86_64-w64-mingw32
        DX_INC=/usr/x86_64-w64-mingw32/include
        DX_LIB=/usr/x86_64-w64-mingw32/lib

        TOOLCHAIN=$GITHUB_WORKSPACE/engine_repo/cmake/toolchains/mingw.cmake

        cmake engine_repo -B engine_build -D CMAKE_TOOLCHAIN_FILE=${TOOLCHAIN} -D MINGW=1 \
          -D DIRECTX_INC_SEARCH_PATHS=$DX_INC -D DIRECTX_LIB_SEARCH_PATHS=$DX_LIB \
          -D CMAKE_BUILD_TYPE=${{ matrix.BUILD_TYPE.VALUE }} \
          -D DV_SHARED=${{ matrix.DV_SHARED.VALUE }}

        cmake --build engine_build

    - name: Test app
      if: false
      run: |
        #sudo cmake --build engine_build --target install
        export DV_HOME=$GITHUB_WORKSPACE/engine_build

        cd engine_repo
        rake new
        cd ..

        export MINGW_PREFIX=/usr/bin/x86_64-w64-mingw32
        DX_INC=/usr/x86_64-w64-mingw32/include
        DX_LIB=/usr/x86_64-w64-mingw32/lib

        TOOLCHAIN=$GITHUB_WORKSPACE/engine_repo/cmake/toolchains/mingw.cmake

        cmake $HOME/projects/UrhoApp -B $HOME/projects/UrhoApp_build -D CMAKE_TOOLCHAIN_FILE=${TOOLCHAIN} -D MINGW=1 \
          -D DIRECTX_INC_SEARCH_PATHS=$DX_INC -D DIRECTX_LIB_SEARCH_PATHS=$DX_LIB \
          -D CMAKE_BUILD_TYPE=${{ matrix.BUILD_TYPE.VALUE }} \
          -D DV_SHARED=${{ matrix.DV_SHARED.VALUE }}

        cmake --build $HOME/projects/UrhoApp_build
